FROM node:18

# Carpeta de trabajo para el SPA
WORKDIR /app

# Copia los archivos del SPA
COPY SPA/ ./

# Instala las dependencias del SPA
RUN npm install

# Compila la aplicación (si es necesario) o simplemente sirve los archivos estáticos
CMD ["npm", "start"]  # O el comando adecuado para tu SPA
