services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    network_mode: "bridge"  
    ports:
      - "1883:1883"  # Puerto estándar de Mosquitto MQTT
    volumes:
      - ./mosquitto/config:/mosquitto/config
     # - ./mosquitto/data:/mosquitto/data
      #- ./mosquitto/log:/mosquitto/log

      #- "D:/Carpetas de usuario/Documentos/Repos/TP-Sistema-Distribuidos/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
     #- "C:/Users/admin/Desktop/Distribuidos/cursada 2024/TP-Sistema-Distribuidos/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"

      # - "D:/Carpetas de usuario/Documentos/Repos/TP-Sistema-Distribuidos/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf" #nb
     #- "C:/Users/admin/Desktop/Distribuidos/cursada 2024/TP-Sistema-Distribuidos/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf" 


    restart: unless-stopped
